### ISSUE TITLE
Más problemas con los "estados"

### ISSUE THREAD

**Issue by ajruedaUJA** [Pedrotc02/DAE2024-25#2]
¿Qué significa CONFIRMADA? Una solicitud puede recibir una confirmación parcial: que pidas 3 plazas y te den 2.

```java
public enum EstadoSolicitud {
    PENDIENTE,
    CONFIRMADA,
    CANCELADA;
}
```

**Comment by tjaj0001** [comment]
Añadidas solicitudes parciales.
